create table loja(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, razao_social VARCHAR(50) NOT NULL, cnpj CHAR(14) NOT NULL, contato VARCHAR(50) NOT NULL, valor_caixa DECIMAL(8,2) NOT NULL);
create table pessoa(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(50) NOT NULL, telefone VARCHAR(50) NOT NULL, cpf CHAR(11) NOT NULL, id_loja BIGINT NOT NULL, FOREIGN KEY (id_loja) REFERENCES loja(id));
create table funcionario(id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, login VARCHAR(100) NOT NULL UNIQUE KEY, senha VARCHAR(50) NOT NULL, id_pessoa BIGINT NOT NULL, FOREIGN KEY(id_pessoa) REFERENCES pessoa(id));
create table venda(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, data DATETIME NOT NULL, id_cliente BIGINT NOT NULL, id_vendedor BIGINT NOT NULL, FOREIGN KEY (id_cliente) REFERENCES pessoa(id), foreign key(id_vendedor) references funcionario(id));
create table item(id BIGINT not null auto_increment primary key, nome varchar(200) not null, valor decimal(8,2) not null, qtde_estoque int not null, qtde_alerta_estoque int, id_loja bigint not null, foreign key(id_loja) references loja(id));
create table item_venda(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, id_venda bigint not null, id_item bigint not null, qtde int not null, valor_unitario decimal(8,2) not null, foreign key(id_venda) references venda(id), foreign key(id_item) references item(id));
create table fornecedor(id bigint not null auto_increment primary key, razao_social varchar(50) not null, cnpj char(14) not null, contato varchar(50) not null, id_loja bigint not null, foreign key(id_loja)references loja(id));
create table item_fornecedor(id bigint not null auto_increment primary key, id_fornecedor bigint not null, id_item bigint not null, valor_compra decimal(8,2) not null, foreign key (id_fornecedor) references fornecedor(id), foreign key (id_item) references item(id));
create table pedido_compra(id bigint not null auto_increment primary key, data datetime not null, id_funcionario bigint not null, foreign key (id_funcionario) references funcionario(id));
create table pedido_compra_item_fornecedor(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, id_item_fornecedor bigint not null, id_pedido_compra bigint not null, valor_unitario decimal(8,2) not null, qtde int not null, foreign key (id_item_fornecedor) references item_fornecedor(id), foreign key (id_pedido_compra) references  pedido_compra(id));

